//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 03:34:20 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gigaforce.io/testsoap/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.gigaforce.testsoap.webservice;
